services:
  - type: web
    name: kelas-x-tkj
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: /var/www/html/database.db
      - key: UPLOAD_PATH
        value: /var/www/html/public/uploads
      - key: BACKUP_PATH
        value: /var/www/html/backups
